### ISSUE TITLE
Fiks darkmode på eventdialog

### ISSUE THREAD

**Issue by Zenjjim** [tihlde/Kvark#201]

**Comment by superspeed500** [comment]
I have looked into to this issue and have found out that there was a missing catch that resulted in an error when someone tried to unregister from an event. The issue was caused by an API call that checks for a userevent object after the object is deleted. I think it might be a good idea to rewrite the code so it won't send out an API call for a object that is known to not exist.

Is that the issue this is referring to or is there another problem? I have not been able to reproduce any other issues in light or dark mode using Firefox or Safari on macOS.
